services:
  spring-kafka-consumer-first:
    build: ./spring-kafka-consumer-first
    container_name: spring-kafka-consumer-first
    environment:
      SPRING_PROFILES_ACTIVE: container,forward

  kafka-producer-one:
    build: ./spring-kafka-producer-one
    container_name: spring-kafka-producer-one
    environment:
      SPRING_PROFILES_ACTIVE: container,forward
    ports:
      - "8080:8080"

  kafka-producer-two:
    build: ./spring-kafka-producer-two
    container_name: spring-kafka-producer-two
    environment:
      SPRING_PROFILES_ACTIVE: container,forward
    ports:
      - "8085:8085"

  kafka-producer-three:
    build: ./spring-kafka-producer-three
    container_name: spring-kafka-producer-three
    environment:
      SPRING_PROFILES_ACTIVE: container,forward
    ports:
      - "8086:8086"