server:
  port: 8083

spring:
  application:
    name: consumer-application-second

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      # Important!
      # In case you publish to a 'dead letter topic' your consumer application becomes
      # a producer as well! So you need to specify the producer properties!
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    consumer:
      group-id: my-consumer-group-second
      auto-offset-reset: earliest
      # Configures the Spring Kafka ErrorHandlingDeserializer that delegates to the 'real' deserializers
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # Tells KafkaAvroDeserializer to look up the SpecificRecord class (the generated Java Class based on our Avro Schema)
        specific.avro.reader: true
        # Delegate deserializers
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer

    properties:
      schema.registry.url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: "*"