server:
  port: 8086
spring:
  application:
    name: producer-application-3

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      client-id: ${spring.application.name}
      properties:
        auto.register.schemas: false
        avro.remove.java.properties: true
        # We don`t auto register, but the schema is incompatible,
        # so we set this to get a more meaningful message instead of schema not found
        # It is not using the schema in the java code
        use.latest.version: true


    properties:
      schema.registry.url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  producer:
    enabled: true
    rate: 3000


